-- Provider-neutral call identifiers, and persisted conversation transcripts.
--
-- `openai_session_id` was carrying ElevenLabs conversation ids and Cartesia session ids
-- as well, because adding a second provider was cheaper than migrating the column. The
-- name then said something untrue about most of the rows in it, and every future provider
-- made that worse. `provider_session_id` says what the value is; `provider` records which
-- backend produced it, which nothing recorded before.
ALTER TABLE calls RENAME COLUMN openai_session_id TO provider_session_id;
ALTER TABLE calls ADD COLUMN IF NOT EXISTS provider text
  CHECK (provider IS NULL OR provider IN ('openai', 'elevenlabs', 'cartesia'));

-- Existing rows predate per-business provider selection, so the only honest backfill is
-- the provider each business is configured for now. Rows whose business has no agent are
-- left null rather than guessed at.
UPDATE calls
   SET provider = agent_configs.voice_provider
  FROM agent_configs
 WHERE agent_configs.business_id = calls.business_id
   AND calls.provider IS NULL
   AND calls.provider_session_id IS NOT NULL;

-- Conversation transcripts.
--
-- Turns were written to stdout and nowhere else, which is the worst of both: no call
-- review, no QA and no analytics, while the caller's words still ended up in a log
-- aggregator with no retention policy attached. Storing them in a table means they can be
-- read by the people who should see them, and deleted on a schedule.
CREATE TABLE IF NOT EXISTS call_transcripts (
  -- Generated by the application, like every other id in this schema, so the database
  -- needs no uuid extension.
  id uuid PRIMARY KEY,
  call_id uuid NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  business_id uuid NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  -- 'caller' is the person on the phone; 'agent' is Callora.
  speaker text NOT NULL CHECK (speaker IN ('caller', 'agent')),
  content text NOT NULL CHECK (char_length(content) BETWEEN 1 AND 8000),
  -- Ordering within a call. Sequence rather than a timestamp, because two turns can land
  -- in the same millisecond and the order is what makes a transcript readable.
  turn integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (call_id, turn)
);

-- Reading one call's transcript in order is the only access pattern that matters.
CREATE INDEX IF NOT EXISTS call_transcripts_call_turn_idx
  ON call_transcripts (call_id, turn);

-- Retention sweeps delete by age across every tenant at once.
CREATE INDEX IF NOT EXISTS call_transcripts_created_at_idx
  ON call_transcripts (created_at);
